resolver: lts-7.4
extra-deps:
  - Ranged-sets-0.3.0
  - hasql-pool-0.4.1
  - hasql-transaction-0.4.5.1
# extra-include-dirs:
#   [/nix/store/hyz7jzia0zih3z3g7g17z1ib11qk9m5h-postgresql-9.5.4/include/]
# extra-lib-dirs:
#   [/nix/store/hyz7jzia0zih3z3g7g17z1ib11qk9m5h-postgresql-9.5.4/lib/,
#     /nix/store/clp627rkaqz8pn0h658vmsx32j5s3srq-openssl-1.0.2j/lib/
#   ]
ghc-options:
  postgrest: -O2 -Werror -Wall -fwarn-identities
nix:
  enable: true
  shell-file: shell.nix
